Fj20200811 01 (singularity remote builder)
aistairc/abci-docs pull request #176
Opened 2020-08-12 00:11 UTC by ABCI-FJSE

Singularity の remote builder について、まずは日本語版のユーザガイドを作成しましたのでご確認ください。
以下、対応を検討中のためいったん記載しておりますが、対応が完了次第、差し替えの予定です。
* コンテナの一覧表示について。まずは singularity search を記載しております。
* コンテナの削除について。singularity delete については、代替手段をいったん記載しております。

2020-08-12 06:56 UTC, ogawa commented
ABCIアカウント名とは？他の例ではusernameとなっており、説明されていない用語を使う理由がありません。また、英語版と共通化するため、実行例の中でnon-ascii文字を使うべきではありません。

2020-08-24 11:34 UTC, s-yama requested changes
章の先頭に、制限事項を列挙お願いします。
　#2343 エンドポイントにあるイメージ一覧の取得に不具合がある。
　#2377 回避手段はあるが、削除機能に不具合がある。
　Keystore に登録した公開鍵の削除はサポートしていない。
　ABCI内のLibrary に push したイメージは、その時点で ABCI ユーザの誰もが入手可能な状態になる。アクセス制限を行うことは出来ない。
　イメージのアップロードに失敗することがある。 https://my.redmine.jp/aist.rp-ith/issues/2377#note-4
　その他、制限事項はすべて章の先頭にリストアップすること。（アップロードできるイメージサイズの制限等）
Singularity Enterpriseという単語は使わないこと。
SingularityPRO の用語で統一すること。
コマンド出力の例を掲載する場合は、出来るだけascii文字列を使うこと、例えばアカウント名ではなくusernameとすること。

2020-08-28 10:39 UTC, ahama commented
こちら、いただいた内容を元に remote builder のページの準備を進めています。作業としては引き継いだと考えていただいて大丈夫です。

2020-08-28 15:25 UTC, ahama commented
このブランチの続きで進めようと思ったのですが、改行コードの違いもあり、いったん整えてから別のブランチに入れて進めます。いただいた内容を基にさせていただくのですが、このプルリクエストは closeさせていただきます。

2020-09-29 03:00 UTC, closed without merging