Fj20201224 00
aistairc/abci-docs pull request #244
Opened 2020-12-24 05:47 UTC by ABCI-FJSE

[#2725](https://my.redmine.jp/aist.rp-ith/issues/2725) の対応で、クラウドストレージアカウントの削除について記載します。

2021-01-13 00:16 UTC, s-yama commented on en/docs/faq.md
> +    - The suffix of the deleted Cloud Storage Account will be a missing number. Foe example, if an ABCI user belongs to a group and the user have 2 Cloud Storage Accounts 'aaa00000aa.1' and 'aaa00000
下記を修正お願いします。
修正前：
Foe example, if an ABCI user belongs to a group and the user have 2 Cloud Storage Accounts 'aaa00000aa.1' and 'aaa00000aa.2'.
修正後：
For example, assume that an ABCI user belongs to a group and the user have 2 Cloud Storage Accounts 'aaa00000aa.1' and 'aaa00000aa.2'.

修正前：
Cloud Storage Account will be able to issue until 'aaa00000aa.11'
修正後：
Cloud Storage Account can be issued up to 'aaa00000aa.11'.

2021-01-13 00:17 UTC, s-yama requested changes
コメントした箇所（英文）を修正お願いします。

2021-01-13 08:53 UTC, ABCI-FJSE commented
ご指摘頂いた箇所（英文）を修正しました。

2021-01-19 16:04 UTC, ahama commented
この内容を私の方で "アカウントとアクセスキー" のページに移そうかと考えています。ちょっとお待ちください。

2021-01-27 08:52 UTC, ahama commented
移動して更新しましたので、 @s-yama  さん、すみませんが確認して問題なければマージをお願いします。

2021-01-27 09:40 UTC, s-yama reviewed
内容を確認しました。これで良いと思います。mergeに進みます。

2021-01-28 00:34 UTC, merged