mod 9.Linux Containers
aistairc/abci-docs pull request #245
Opened 2021-01-08 10:03 UTC by ABCI-FJSE

Redmineの以下チケットに関するUser Guideの修正です。
https://my.redmine.jp/aist.rp-ith/issues/2654

「9.Linux Containers」のページを修正しています。
実行する順番にあわせて、イメージファイルの作成を先に記載して、その後にコンテナの実行を記載するように変更しました。
また、コンテナを実行する部分については、コンテナの実行にまとめて記載しています。

2021-01-09 03:15 UTC, stakizawa commented
日本語版にて、章タイトルを「Singularityの実行」 -> 「コンテナの実行」に変えているので、l.205のリンクタイトルと食い違っていますので、正してください。

2021-01-12 09:21 UTC, ABCI-FJSE commented
日本語版の09.mdについて、205行目のリンクタイトルを「Singularityの実行」から「コンテナの実行」に修正しました。

2021-01-19 08:35 UTC, stakizawa requested changes
当初依頼していた修正の本質とはずれますが、少しの英文の修正と、newgrpの記述についての捕捉のお願いがあります。

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +In the SingularityPRO 3.5 environment of the ABCI system, You can build container image files using `fakeroot` option.
You -> you

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +    You cannot build a container image from the recipe file in Singularity 2.6 environment.  To use your custom container image, you adapt your own server environment to the ABCI environment (the ver
the recipe file -> a recipe file
すでに示されているrecipe fileを指しているわけではないので、aの方が適切です。

2021-01-19 08:35 UTC, stakizawa commented on ja/docs/09.md
> +なお、 上記コマンドをグループ領域(/groups1, /groups2)配下で実行するとエラーが発生します。その場合、singularityコマンドを実行する前に以下のように`id -a`コマンドで所属するグループを確認の上、`newgrp`コマンドを実施いただくことで回避可能です。
以前から書かれていた内容なのですが、よく理解できていないので教えてください。

グループディレクトリ以下にコンテナイメージを書き出したい場合、そのグループディレクトリを所有するLinuxグループにログインし直せ、ということなのでしょうか？

でしたら、「上記コマンドをグループ領域(/groups1, /groups2)配下で実行するとエラーが発生します」は正しくなく、「イメージファイル(ubuntu.sif)の出力先をグループ領域(/groups1, /groups2)にするとエラーが発生します」が正しい内容になります。

また、`id -a`（-aはignoreされるようなので実際は`id`）を実行した場合、複数のグループに属す場合はたくさん表示されますが、どれを選べば良いか、指針が十分に示されていません。上記の私の理解が正しければ、イメージ出力先グループ領域の所有グループを選ぶように明記ください。

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +If the above command is executed under the group area (/ groups1,/groups2), an error occurs. This can be avoided by executing the `newgrp` command after checking the group to which the `id -a` comman
日本語版の修正に伴い、修正ください。

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +You can also use the `singularity run` command to run a container image exposed in Docker Hub.
exposed -> published

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +The following sample is execution of Singularity using caffe2 container image published in Docker Hub.
The following sample executes a Singularity container using caffe2 container image published in Docker Hub.

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +`python sample.py` is executed on Singularity container started by `singularity run` command.
`python sample.py` is executed in the container started by `singularity run` command.

2021-01-19 08:35 UTC, stakizawa commented on en/docs/09.md
> +The container image is downloaded at first startup and cached in home area.
at the first startup

2021-01-25 09:57 UTC, ABCI-FJSE commented on en/docs/09.md
> +In the SingularityPRO 3.5 environment of the ABCI system, You can build container image files using `fakeroot` option.
修正しました。

2021-01-25 09:58 UTC, ABCI-FJSE commented on en/docs/09.md
> +    You cannot build a container image from the recipe file in Singularity 2.6 environment.  To use your custom container image, you adapt your own server environment to the ABCI environment (the ver
修正しました。

2021-01-25 09:58 UTC, ABCI-FJSE commented on ja/docs/09.md
> +なお、 上記コマンドをグループ領域(/groups1, /groups2)配下で実行するとエラーが発生します。その場合、singularityコマンドを実行する前に以下のように`id -a`コマンドで所属するグループを確認の上、`newgrp`コマンドを実施いただくことで回避可能です。
本件、ご指摘の通りとなります。記載を修正しました。

2021-01-25 09:59 UTC, ABCI-FJSE commented on en/docs/09.md
> +If the above command is executed under the group area (/ groups1,/groups2), an error occurs. This can be avoided by executing the `newgrp` command after checking the group to which the `id -a` comman
修正しました。

2021-01-25 09:59 UTC, ABCI-FJSE commented on en/docs/09.md
> +You can also use the `singularity run` command to run a container image exposed in Docker Hub.
修正しました。

2021-01-25 09:59 UTC, ABCI-FJSE commented on en/docs/09.md
> +The following sample is execution of Singularity using caffe2 container image published in Docker Hub.
修正しました。

2021-01-25 09:59 UTC, ABCI-FJSE commented on en/docs/09.md
> +`python sample.py` is executed on Singularity container started by `singularity run` command.
修正しました。

2021-01-25 10:00 UTC, ABCI-FJSE commented on en/docs/09.md
> +The container image is downloaded at first startup and cached in home area.
修正しました。

2021-01-26 01:56 UTC, merged