Added the FAQ entry. "What is the new ABCI Group area and data migration"
aistairc/abci-docs pull request #264
Opened 2021-04-19 02:38 UTC by ttakayuki

FAQ(日本語、英語)に新ABCIグループ領域とデータ移行についての説明を追加しました。
mkdocs serveにより生成物を作成したあと、Safari 14.0.3にて書式を確認しました。

2021-04-19 03:34 UTC, ogawa commented
To devel-202105

2021-04-19 03:39 UTC, ttakayuki commented
> To devel-202105

Pull Requestの提出先を devel-202105ブランチに変更します。

2021-04-19 04:46 UTC, s-yama requested changes
戸澤さん、
アップロードありがとうございました。タイトルのタグが
日本語版
http://localhost:8001/faq/#q-abci
英語版
http://localhost:8002/faq/#q-what-is-the-new-abci-group-area-and-data-migration
となり、異なっているのですが、同一に設定いただけませんか？

2021-04-19 05:19 UTC, ttakayuki commented
```
タイトルのタグが
日本語版
http://localhost:8001/faq/#q-abci
英語版
http://localhost:8002/faq/#q-what-is-the-new-abci-group-area-and-data-migration
となり、異なっているのですが、同一に設定いただけませんか？
```

日本語版のタイトルタグ(アンカー)を英語版に合わせて q-what-is-the-new-abci-group-area-and-data-migration に修正しました。

2021-04-19 05:32 UTC, s-yama approved these changes
戸澤さん
修正ありがとうございました。内容確認しました。

2021-04-19 08:18 UTC, HidemotoNakada commented
## Q. 新ABCIグループ領域とデータ移行について知りたい

2021年度のABCIグループ領域について説明します。

これまで`/groups[1-2]/gAA50NNN`（旧領域）をご利用頂いていた皆様には、4月から新しく `/groups/gAA50NNN`（新領域）が利用可能になります。
それぞれ、すべてのインタラクティブノードとすべての計算ノードで、利用可能なディレクトリです。

旧領域を、今後、新領域へデータ移行します。
/groups2, /groups1, /fs3 の順にデータ移行予定、完了まで約1年の予定です。

以下にデータ移行について説明します。

**(1) 新領域/groups/gAA50NNNについて**

* 新領域には、旧領域に設定していたディスククォータの2倍まで書き込み可能です。データ移行完了までの一時的な増量です。
* 旧領域のファイルの実体は、新領域の `/groups/gAA50NNN/migrated_from_SFA_GPFS/` にコピーされる予定です。
* データ移行進捗に伴い旧領域のファイルが新領域にコピーされますが、データ移行完了までの期間は、利用者様から参照不可・アクセス不可です。参照不可ですがクォータの利用量は増えますので、ご注意ください。
* データ移行完了後は、元のクォータ値に戻します（猶予期間を設ける予定です）。

**(2) 旧領域/groups[1-2]/gAA50NNNについて**

**1. データ移行中**

* 運用側がデータ移行するため、利用者から見るとシステム側が自動的にデータ移行を実施しているように見えます。
* データ移行中に、利用者様は自由に旧領域にR/W可能、ファイルの削除も可能です。
* データ移行する量を減らすために、旧領域には、可能な限り新規ファイルを置かないでください。不要なファイルは削除してください。可能な範囲で構いません、ご理解お願いいたします。（なお、データ移行完了後は、この制限は無くなります。）

**2.データ移行完了のための参照不可期間について**

* データ移行完了の確認のために、旧領域を参照不可の期間が数日発生する予定です。
* その期間、新領域は読み込み/書き込み/削除可能予定です。
* 今までと同じパス `/groups[1-2]/gAA50NNN` でアクセス可能にするために、運用側がシンボリックリンクを変更します。

**3.データ移行完了後について**

* 今までと同じパス `/groups[1-2]/gAA50NNN` でアクセス可能です。
* 旧領域のファイルの実体は、新領域の `/groups/gAA50NNN/migrated_from_SFA_GPFS/` にコピーされた状態になる予定です。

2021-04-19 09:37 UTC, HidemotoNakada commented
## Q. What are the new ABCI Group area and data migration?

In FY2021, we will have a data migration for the Group Area storage. The existing group area (The **Old Area** ) will not be accessible from the coming new computing resources. Therefore we need to create a new group area (The **New Area**) and migrate all the data stored in the **Old Area** to the **New Area**. The data copy is managed by the operating team, so the users do not have to take care of the copy process.

A user group who are using the **Old Area** `/groups[1-2]/gAA50NNN` had been also allocated the **New Area** at ` /groups/gAA50NNN`. Both of the **Old and New Area** are accessible all the existing interactive nodes and computing nodes.


以下にデータ移行について説明します。

**(0) Basic Strategy **

旧領域のファイルを新領域に運用側がバックグラウンドでコピーします。
利用者様は、旧領域をそのままお使いいただけますが、可能な限り新領域のご利用をお願いします。
コピー完了後、リンクの切り替えによって旧領域への参照を新領域への参照に書き換えます。
We are going to explain the ABCI Group area in FY2021 for ABCI users using `/groups[1-2]/gAA50NNN` .

The new area ( `/groups/gAA50NNN` ) have been available since April 7th for ABCI users using `/groups[1-2]/gAA50NNN` (old area).
Both new and old area is accessible from all interactive nodes and all compute nodes.

Data in the old area will be migrated to the new area in the future.
The data migration is scheduled in the order of /groups2, /groups1, /fs3, and it will be completed in about one year.

Here is more detailed information.

**(1) The new area /groups/gAA50NNN**

* A quota that is twice the value of the old area is set in the new area. This is a temporary increase until the data migration is completed.
* The files in the old area will be copied to `/groups/gAA50NNN/migrate_from_SFA_GPFS/` in the new area.
* As the data migration progresses, the files in the old area will be copied to the new area, but you cannot access them until the data migration is completed. Please note that the quota usage will increase, although the files cannot be accessed.
* After the data migration is completed, the original quota value will be restored (a grace period will be provided).

**(2) The old area /groups[1-2]/gAA50NNN**

**1. During the data migration**

* Since the administrator will perform the data migration, it seems that the data migration is automatically performed by the system from the user's point of view.
* During the data migration, you can read, write and delete files in the old area.
* In order to reduce the amount of the data migration, please do not put new files in the old area as much as possible. Please delete unnecessary files in the old area as much as possible.  It doesn't matter as much as you can.  (This restriction will be removed after the data migration is completed.)

**2. At the end of the data migration**

* At the end of the data migration, there will be several days of period while you cannot access the old area.
* During that period, you can R/W and delete files in the new area.
* The system administrator will change the symbolic link so that you can access the migrated data in the new area with the same path `/groups[1-2]/gAA50NNN` as before.

**3. After the data migration is completed**

* You can access the migrated data in the new area  with the same path `/groups [1-2]/gAA50NNN` as before.
* The files in the old area will be copied to `/groups/gAA50NNN/migrate_from_SFA_GPFS/` in the new area.

2021-04-19 12:14 UTC, ttakayuki commented
中田様。確認と文章の作成ありがとうございます。
書式のチェックを行い、Pull Requestを更新しました。

2021-04-20 00:54 UTC, s-yama approved these changes
中田さん
文章作成ありがとうございました。
戸澤さん
書式チェックとpull request送信ありがとうございました。
内容確認しました。

2021-04-20 02:15 UTC, ogawa commented
敬語を廃すること。

利用者様 => 利用者
お使いいただける => 使える

2021-04-20 02:17 UTC, ogawa commented
> データ移行完了の確認のために、旧領域を参照できない期間が数日発生する予定です。

この作業の後、旧領域にアクセスできるのか？
旧領域をコピーした新領域上のファイル、ディレクトリにアクセスできるだけではないか？
もしそうでないとすると、旧領域はいつアクセスできなくなるのか？

不明瞭なので修正すること。

2021-04-20 02:33 UTC, HidemotoNakada commented
> データ移行完了の確認のために、旧領域を参照できない期間が数日発生する予定です。

この期間は旧領域にあったデータが、旧領域としても新領域としてもアクセスできない、という理解です。この期間のあとで新領域としてアクセス可能になると。

> データ移行完了の確認のために、旧領域に置かれていたデータが、旧領域としても新領域としても参照できない期間が数日発生する予定です。この期間の後、旧領域に置かれていたデータは、新領域からアクセスできるようになります。

ぐらいでしょうか。

2021-04-20 02:42 UTC, s-yama reviewed
小川さん、
質問いただきました件、回答します。
「データ移行完了の確認のために、旧領域を参照できない期間が数日発生する予定です。」
質問（１）この作業の後、旧領域にアクセスできるのか？
回答（１）旧領域/groups[1-2]/gAA50NNNにはアクセスできません。
質問（２）旧領域をコピーした新領域上のファイル、ディレクトリにアクセスできるだけではないか？
回答（２）そのとおりです。

または、利用者に、「新領域上にコピーされたファイル・ディレクトリと、旧領域のファイル・ディレクトリを比較する期間を与える」という案もあります。その場合は、前述の回答とは異なる回答となります。
私はこの期間を不要と考えていますが、富士通さんは4/19の会議で、この期間を持つことを提案しました。4/19の会議で結論は出なかったという理解です。
私は、仮り決めで、「この期間を持たない」前提で書くべきと考えています。その場合は、前述の回答のとおりとなります。

2021-04-20 04:50 UTC, ttakayuki commented
* 敬語表現を外しました。
* 単語にまとまりがなかったのでなるべく統一しました。意味が変わっていないかご確認頂けますでしょうか。

2021-04-20 04:51 UTC, s-yama commented on ja/docs/faq.md
> -* データ移行完了の確認のために、旧領域を参照できない期間が数日発生する予定です。
中田さんのコメントのように、下記のような修正をお願いします。
修正前：
データ移行完了の確認のために、旧領域を参照できない期間が数日発生する予定です。
修正後：
データ移行完了の確認のために、旧領域のデータについて、旧領域としても新領域としても参照できない期間が数日発生する予定です。この確認期間の後に「データ移行完了」が確認され、旧領域に置かれていたデータは、新領域からアクセスできるようになります。

2021-04-20 05:03 UTC, s-yama commented on ja/docs/faq.md
> +* データ移行完了後、`/groups[1-2]/gAA50NNN`は、新領域`/groups/gAA50NNN/migrated_from_SFA_GPFS/`へのシンボリックリンクで実現されます。
下記を追記お願いします。

データ移行完了後は、元の旧領域（元の/groups[1-2]/gAA50NNN）へアクセスできなくなります。

2021-04-20 05:16 UTC, ttakayuki commented on ja/docs/faq.md
> +* データ移行完了後、`/groups[1-2]/gAA50NNN`は、新領域`/groups/gAA50NNN/migrated_from_SFA_GPFS/`へのシンボリックリンクで実現されます。
> 元の旧領域(元の...)

だと冗長だと思うので、次のように直したいと思います。

* データ移行完了後、旧領域上の`/groups[1-2]/gAA50NNN`にはアクセスできなくなります。

2021-04-20 05:19 UTC, s-yama commented on ja/docs/faq.md
> +* データ移行完了後、`/groups[1-2]/gAA50NNN`は、新領域`/groups/gAA50NNN/migrated_from_SFA_GPFS/`へのシンボリックリンクで実現されます。
了解しました。

2021-04-20 05:35 UTC, s-yama reviewed
戸澤さん
修正ありがとうございました。日本語版を確認しました。これで良いと思います。
英語版を、日本語版にあわせて修正お願いします。

2021-04-20 06:05 UTC, ogawa commented
注意深く書いてください：
全利用者データのコピー完了までには1年間かかることを予定しています => 1年間かかる予定です
利用をお願いします => 利用してください

> データコピーにともないディスククォータ使用量が増大しますが、害はありません。

ディスククオータ使用量が増加とは？また害がない理由を説明するつもりがないなら不要ではないかと思います。

2021-04-20 06:21 UTC, s-yama commented on ja/docs/faq.md
> +* データコピーにともないディスククォータ使用量が増大しますが、害はありません。
下記の修正はいかがでしょうか。
修正前：
データコピーにともないディスククォータ使用量が増大しますが、害はありません。
修正後：
新領域のデータコピーのフォルダにはアクセスできませんが、データコピーにともないディスククォータ使用量が増大します。クォータ超過しないようご注意ください。超過しそうな場合は、グループ領域のクォータ増量を利用者ポータルから申請ください。

2021-04-20 06:32 UTC, ogawa commented on ja/docs/faq.md
> +* データコピーにともないディスククォータ使用量が増大しますが、害はありません。
増えるのは、ディスククオータ使用量ですか、ディスク使用量ですか。

言いたいのは、以下では？

* データコピーにともないディスク使用量が増加します。このため、移行期間中は、新領域のクォータ値を旧領域のクォータ値の2倍に設定します。移行完了後、一定の猶予期間を設けて旧領域のクォータ値に戻します。

次にディスククオータはユーザが選べる値ですから、「旧領域のクォータ値」は不明瞭です。ポータルで申請しているグループディスク量ではありませんか？

2021-04-20 06:34 UTC, s-yama commented on ja/docs/faq.md
> +* データコピーにともないディスククォータ使用量が増大しますが、害はありません。
はい、ご指摘のとおりです。

2021-04-20 08:12 UTC, ttakayuki commented on ja/docs/faq.md
> +* データコピーにともないディスククォータ使用量が増大しますが、害はありません。
「クォータ値」ではなく「グループディスク量/ディスク量」が適切ということでしょうか?

修正するとしたらこうでしょうか。
* データコピーにともないディスク使用量が増加します。このため、移行期間中は、 **新領域のグループディスク量** を旧領域のディスク量の2倍に設定します。移行完了後、一定の猶予期間を設けて旧領域のディスク量に戻します。

2021-04-20 08:57 UTC, ttakayuki commented
* 日本語文書において、婉曲な表現を修正しました。
* 日本語の修正に合わせて英語版を更新しました。

2021-04-20 09:09 UTC, ogawa commented
> 次にディスククオータはユーザが選べる値ですから、「旧領域のクォータ値」は不明瞭です。ポータルで申請しているグループディスク量ではありませんか？

対応してください。

「旧領域のディスク量」とはなんですか？クオータなのか使用量なのか不明瞭です。

ユーザはいつでもディスククオータを変更できます。「旧領域のディスク量(クオータ)」とは無関係です。
つまり、「○○で指定(申請)したディスククオータの2倍」でなくてはなりません。

2021-04-20 09:15 UTC, ogawa commented
さらにいうと「○○で指定(申請)したディスククオータ」は、旧領域、新領域のディスククオータにどのような影響を与えますか？

2021-04-20 12:22 UTC, ttakayuki commented
> ユーザはいつでもディスククオータを変更できます。「旧領域のディスク量(クオータ)」とは無関係です。
> つまり、「○○で指定(申請)したディスククオータの2倍」でなくてはなりません

申し訳ございません。ABCIにまだ詳しくないため、対応にかなり時間がかかっています。 

新領域のディスククォータの値の基準が、利用者が利用者ポータルで申請した値の2倍であるということでしょうか。
旧領域のクォータと、利用者が利用者ポータルで申請したクォータは同じものであると認識していました。

文章を次のように修正しました。

* データコピーにともないディスク使用量が増加します。このため、移行期間中は、新領域のクォータ値を、利用者ポータルで申請したグループディスクの2倍の値に設定します。移行完了後、一定の猶予期間を設けて、利用者ポータル上のクォータ値に戻します。

2021-04-20 14:29 UTC, ogawa commented
> > ユーザはいつでもディスククオータを変更できます。「旧領域のディスク量(クオータ)」とは無関係です。
> > つまり、「○○で指定(申請)したディスククオータの2倍」でなくてはなりません
> 
> 申し訳ございません。ABCIにまだ詳しくないため、対応にかなり時間がかかっています。
> 
> 新領域のディスククォータの値の基準が、利用者が利用者ポータルで申請した値の2倍であるということでしょうか。
> 旧領域のクォータと、利用者が利用者ポータルで申請したクォータは同じものであると認識していました。
> 
> 文章を次のように修正しました。
> 
> * データコピーにともないディスク使用量が増加します。このため、移行期間中は、新領域のクォータ値を、利用者ポータルで申請したグループディスクの2倍の値に設定します。移行完了後、一定の猶予期間を設けて、利用者ポータル上のクォータ値に戻します。

確認した上で修正すればよいです。

2021-04-20 15:12 UTC, ogawa commented
「ABCIグループ領域」という言葉は未定義。「グループディスク」「グループ領域」

2021-04-21 03:05 UTC, ttakayuki commented
小川様からコメントいただいた分を修正しました。
すみません、英語版はすぐには対応できそうにないためひとまず書式だけ更新しました。

2021-04-21 05:10 UTC, s-yama reviewed
戸澤さん
修正ありがとうございました。日本語確認しました。私はこれでOKと思います。
引き続き、英語版の修正をお願いします。

2021-04-21 08:36 UTC, ttakayuki commented
コミット74989ccの修正について、英語版のFAQも対応させました。

2021-04-23 00:42 UTC, s-yama approved these changes
谷村さんからSLACKで下記のメッセージを受領しましたので、承認いただいたものと理解します。
4/23 8:58　「各グループの切替時期や切替の進め方は様子が分かった段階で情報をアップデートするべきかと思います。それ以外は特にありません。」
mergeへ進みます。

2021-04-23 00:43 UTC, merged