Added the s3fs-fuse usage.
aistairc/abci-docs pull request #309
Opened 2021-09-15 02:42 UTC by ttakayuki

Fixed a code block in the usage.md(ja) file.

2021-09-16 04:15 UTC, u-kawasaki approved these changes

2021-09-17 09:34 UTC, s-yama commented on en/docs/abci-cloudstorage/s3fs-usage.md
> +Please refer to [the ABCI Portal Guide](https://docs.abci.ai/portal/ja/02/#282) for how to issue an access key.
日本語を参照しているようです。下記の修正をお願いします。
修正前：(https://docs.abci.ai/portal/ja/02/#282)
修正後：(https://docs.abci.ai/portal/en/02/#282)

2021-09-17 09:42 UTC, s-yama commented on en/docs/abci-cloudstorage/s3fs-usage.md
> +If you mount a bucket using `s3fs-fuse` in a job secured by the On-demand, Spot service, it will be automatically unmounted at the end of the job.
下記を修正お願いします。
修正前：If you mount a bucket using s3fs-fuse in a job secured by the On-demand, Spot service,
修正後：If you mount a bucket using s3fs-fuse in a job obtained by the On-demand or Spot service,

2021-09-17 09:43 UTC, s-yama requested changes
２か所コメントしました。修正お願いします。

2021-09-21 08:36 UTC, ttakayuki commented
山本様に指摘いただいた2点を修正しました。
* 英語版における、ABCI Portal GuideのURL
* 英語版の文章

2021-09-22 03:50 UTC, s-yama approved these changes
修正ありがとうございました。

2021-09-22 08:28 UTC, stakizawa reviewed
1点コメントしました。

2021-09-22 08:28 UTC, stakizawa commented on en/docs/abci-cloudstorage/s3fs-usage.md
> +Please refer to [the ABCI Portal Guide](https://docs.abci.ai/portal/en/02/#282) for how to issue an access key.
リンク先が正しくないです。英語版の正しいリンク先は以下です。
https://docs.abci.ai/portal/en/02/#282-manage-access-key

2021-09-22 10:25 UTC, ttakayuki commented on en/docs/abci-cloudstorage/s3fs-usage.md
> +Please refer to [the ABCI Portal Guide](https://docs.abci.ai/portal/en/02/#282) for how to issue an access key.
ありがとうございます。英語版のURLを修正しました。

2021-09-22 22:39 UTC, y-tanimura approved these changes

2021-09-22 22:39 UTC, merged