add storage.md about scratch
aistairc/abci-docs pull request #315
Opened 2021-12-10 02:49 UTC by ABCI-FJSE

redmineチケット3946 ( https://my.redmine.jp/aist.rp-ith/issues/3946 ) に関連して、/scratch関連の記載を追加しました。
ご確認のほどよろしくお願いします。
なお、名称については仮で記載させていただきましたので、ご検討のほどよろしくお願いします。

2021-12-10 05:14 UTC, u-kawasaki commented on en/docs/storage.md
> +    In case the free space on this stotrage becomes less than the prescribed values, the files and directorirs, directly in /scratch/(ABCI account)/, which has been equals or more than 40 days will d
I feel grammatically strange. I think the following expression is better:

..., the files and directories, directly in /scratch/(ABCI account)/, which has been 40 days old or more will be deleted automatically.

2021-12-10 09:01 UTC, stakizawa commented
/scratchではdata on mdtが有効になっていたと思います。
そのことの記載と、data on mdtのデフォルト動作・設定、利用者によるMDTに格納するデータの最大サイズの変更についても記載ください。

2021-12-14 06:55 UTC, ttakayuki reviewed
ドキュメントありがとうございます。気になった点についてコメントしますのでご確認ください。
また、コメントにも書きましたが、名称が「**グローバルスクラッチ領域**」に決まりましたので文中の名前を変更してください。

2021-12-14 06:55 UTC, ttakayuki commented on ja/docs/storage.md
> +### 短期利用高速データ領域 {#scratch-area}
AIST側で名称を「グローバルスクラッチ領域」に決めましたので、こちらに変更していただけますでしょうか。英語版だと「Global scratch area」でお願いします。

また、グループ領域とは別ですのでヘッダーのレベルを2(##)としてください。

2021-12-14 06:55 UTC, ttakayuki commented on ja/docs/storage.md
> +    短期利用高速データ領域は、ストレージ全体の空き容量が少なくなった場合に、作成から40日経過した /scratch/(ABCIアカウント名) 直下のファイルおよびディレクトリが自動的に削除されます。削除されたファイルおよびディレクトリについては復元することができませんので、必要に応じて事前にバックアップ願います。
一文が長いので分割してみました、以下では如何でしょうか。

```
グローバルスクラッチ領域は、クリーンアップ機能を備えています。
ストレージ全体の空き容量が少なくなった場合に、作成から40日経過した/scratch/(ABCIアカウント名)直下のファイルおよびディレクトリを自動的に削除します。
削除されたファイルおよびディレクトリは復元できませんので、必要に応じて事前にバックアップしてください。
```

2021-12-14 06:55 UTC, ttakayuki commented on ja/docs/storage.md
> +    短期利用高速データ領域配下に大量のファイルを格納する場合は、/scratch/(ABCIアカウント名) 配下にディレクトリを作成の上、格納いただくことを推奨いたします。
> 格納いただくことを推奨いたします。

ユーザーガイド中に過度な敬語表現は不要と思いますので、「格納することを推奨します。」でお願いします。

2021-12-17 11:42 UTC, ABCI-FJSE commented
/scratch関連の記載について、ご指摘いただいた箇所の修正を実施しました。ご確認のほどよろしくお願いします。

2021-12-20 05:17 UTC, ABCI-FJSE commented
DoMに関する記載について一点ご相談ですが、現在の例は全てmdtの上限64KiBを超えた場合に超えた分のデータはostに格納されるような指定となっていますが、乱用を防ぐために「mdtの上限64KiBを超えた場合をエラーとする」指定を推奨するという考え方もあります。このあたりの書き方についてご指示等ありましたらよろしくお願いします。

2021-12-20 06:42 UTC, ABCI-FJSE commented
DoMの記載の中の lfs setstripe のオプションの説明に誤りがありましたので修正し、本日再pushしました。

2021-12-20 09:37 UTC, ttakayuki reviewed
英語版のtypo、日本語版のDoMに関してコメントを書きましたのでご確認ください。

2021-12-20 09:37 UTC, ttakayuki commented on ja/docs/storage.md
> +| -E | レイアウトサイズを設定。-E #k, -E #m, -E #gとすることで、サイズをKiB,MiB,GiBで設定可能です。 |
* -Eオプションは、「コンポーネントのオフセットを設定」ではないでしょうか? また、 例では -1(eof) を使用していますので、-1の説明もあった方がよいように思います。

2021-12-21 00:18 UTC, s-yama commented on ja/docs/storage.md
> +    ストレージ全体の空き容量が少なくなった場合に、作成から40日経過した/scratch/(ABCIアカウント名) 直下のファイルおよびディレクトリを自動的に削除します。
掃除する条件を記載すべきと思います。
例：
修正前： ストレージ全体の空き容量が少なくなった場合に
修正後：/scratchのファイル領域またはi-node領域の利用率が80%を超過した場合に、
例：
修正前：作成から40日経過した/scratch/(ABCIアカウント名) 直下のファイルおよびディレクトリを自動的に削除します。
修正後：/scratch/(ABCIアカウント名) 直下のファイルおよびディレクトリのうち、削除候補のものを自動的に削除します。最初の削除候補として、最終参照タイムが40日を経過したものが選ばれます。その候補を削除した後に、まだ、/scratchの利用率が80%超過の場合は、作成タイムが40日を経過したものが次の削除候補として選ばれます。ファイル/ディレクトリ作成タイムはlsコマンドで調査できないため、ご自分で記録しておいてください。

2021-12-21 00:21 UTC, s-yama commented on ja/docs/storage.md
> +各利用者は以下の領域を短期利用高速データ領域として利用することが可能です。
下記のような文章を追加お願いします。
例：
グローバルスクラッチ領域のクォータを調査するには、`show_quota` コマンドを実行してください。コマンドの説明については [ディスククォータの確認](getting-started.md#checking-disk-quota) を参照してください。

2021-12-21 00:34 UTC, s-yama commented on ja/docs/storage.md
> +    グローバルスクラッチ領域配下に大量のファイルを格納する場合は、/scratch/(ABCIアカウント名) 配下にディレクトリを作成の上、格納することを推奨します。
「システム更新履歴」の2021/08-12に、下記のような文章を追加お願いします。
グローバルスクラッチ領域の追加に伴い、ドキュメントの「ストレージ」へ「グローバルスクラッチ領域」を追加しました。

2021-12-21 00:37 UTC, s-yama commented on ja/docs/storage.md
> +グローバルスクラッチ領域ではDoM(Data on MDT)機能により、LustreのMDT上にデータを格納することが可能です。
MDTの説明、MDTに置くとパフォーマンスが良い、ストライブの使い方、等の説明がある、Lustreの説明文書へのリンクがあると良いと思います。そのリンクは、ABCI外へのリンクでもよいと思います。

2021-12-21 00:38 UTC, s-yama requested changes
コメントを書きましたので、修正お願いします。

2021-12-21 04:07 UTC, ABCI-FJSE commented on ja/docs/storage.md
> +グローバルスクラッチ領域ではDoM(Data on MDT)機能により、LustreのMDT上にデータを格納することが可能です。
山本様
想定されているのは以下のようなものでしょうか。
https://wiki.lustre.org/Data_on_MDT

2021-12-21 04:20 UTC, s-yama commented on ja/docs/storage.md
> +グローバルスクラッチ領域ではDoM(Data on MDT)機能により、LustreのMDT上にデータを格納することが可能です。
はい、そのとおりです。
ストライプの説明・効果についても、同じように、何か説明の外部リンクを掲載お願いします。

2021-12-21 09:04 UTC, ABCI-FJSE commented
ご指摘いただいた点について修正を実施し、再pushいたしましたのでご確認のほどよろしくお願いします。

2021-12-21 09:33 UTC, s-yama commented on en/docs/storage.md
> +To examine the global scratch space quota, run `show_quota` command. For a description of the command, see [Checking Disk Quota](getting-started.md#checking-disk-quota).
下記を修正お願いします。
修正前：To examine the global scratch space quota, run `show_quota` command. 
修正後：To see the quota value of the global scratch area, issue  `show_quota` command.

2021-12-21 09:36 UTC, s-yama commented on en/docs/storage.md
> +    When the usage of the file area or i-node area of /scratch exceeds 80%, delete candidates are selected based on the last reference time and creation date of files and directories directly under /
下記を修正お願いします。
1
修正前：last reference time
修正後：last access time
2
「/scratch/(ABCIアカウント名) 直下のディレクトリが削除候補になった場合は、そのディレクトリ配下のすべてのファイル/ディレクトリが削除されます。」の英訳が無いので、追加お願いします。

2021-12-22 01:01 UTC, u-kawasaki commented on en/docs/storage.md
> +This storage is shared by interactive nodes and all V and A calculated nodes.
The following terms should be unified: 
"all V and A calculated nodes" --> "all Compute Nodes V and A"

2021-12-22 01:01 UTC, u-kawasaki commented on en/docs/storage.md
> +| -L | Set Layout Type. Specifying ```mdt``` enables DoM. |
The description is duplicated. The above line should be deleted.

2021-12-22 05:14 UTC, ABCI-FJSE commented
コメントいただいた箇所の修正後に再度pushしましたので、ご確認のほどよろしくお願いします。

2021-12-22 05:19 UTC, u-kawasaki approved these changes

2021-12-22 06:56 UTC, ttakayuki commented on en/docs/storage.md
> +    So the deleted files will not be able to be recoverd, please back them up if you need.
修正されていることを確認しました。

2021-12-22 07:18 UTC, ttakayuki reviewed
Warningの箇所の用語を統一/修正していただけますでしょうか。

2021-12-22 07:18 UTC, ttakayuki commented on ja/docs/storage.md
> +    最初の削除候補として、最終参照タイムが40日を経過したものが選ばれます。その候補を削除した後に、まだ、/scratchの利用率が80%超過の場合は、作成日が40日を経過したものが次の削除候補として選ばれます。ファイル/ディレクトリの作成タイムはlsコマンドで調査できないため、ご自分で記録しておいてください。
* 山本様とも相談しましたが、「最終参照タイム」を「最終アクセス時間」に修正していただけますでしょうか。
* 「作成日」と「作成タイム」が混ざっているので「作成日」に統一してください。

2021-12-22 08:58 UTC, ABCI-FJSE commented
コメントいただいた箇所を修正後、再度pushしましたので、ご確認のほどよろしくお願いします。

2021-12-22 09:18 UTC, ttakayuki commented on ja/docs/storage.md
> +    最初の削除候補として、最終参照タイムが40日を経過したものが選ばれます。その候補を削除した後に、まだ、/scratchの利用率が80%超過の場合は、作成日が40日を経過したものが次の削除候補として選ばれます。ファイル/ディレクトリの作成タイムはlsコマンドで調査できないため、ご自分で記録しておいてください。
修正を確認しました。

2021-12-22 09:19 UTC, ttakayuki approved these changes

2021-12-23 05:34 UTC, s-yama approved these changes
私はこれで良いと思います。

2021-12-23 07:05 UTC, s-yama commented on ja/docs/storage.md
> +    最初の削除候補として、最終アクセス時間が40日を経過したものが選ばれます。その候補を削除した後に、まだ、/scratchの利用率が80%超過の場合は、作成日が40日を経過したものが次の削除候補として選ばれます。ファイル/ディレクトリの作成日はlsコマンドで調査できないため、ご自分で記録しておいてください。
谷村さんからコメント受領しました。修正お願いします。(12/23 15時)
修正前：ファイル/ディレクトリの作成日はlsコマンドで調査できないため、ご自分で記録しておいてください。
修正後：ファイル/ディレクトリの作成日はlsコマンドで確認できないため、利用者自身で控えるようにしてください。

2021-12-23 07:05 UTC, s-yama commented on ja/docs/storage.md
> +    グローバルスクラッチ領域配下に大量のファイルを格納する場合は、/scratch/(ABCIアカウント名) 配下にディレクトリを作成の上、格納することを推奨します。
谷村さんからコメント受領しました。修正お願いします。(12/23 15時)
修正前：配下にディレクトリを作成の上、格納することを推奨します。
修正後：配下にディレクトリを作成の上、格納するようにして下さい。

2021-12-23 07:09 UTC, s-yama commented on ja/docs/storage.md
> +グローバルスクラッチ領域ではData on MDT(DoM)機能により、LustreのMDT(メタデータを格納するサーバ)上にデータを格納することが可能です。
谷村さんからコメント受領しました。修正お願いします。(12/23 15時)
修正前：
グローバルスクラッチ領域ではData on MDT(DoM)機能により、LustreのMDT(メタデータを格納するサーバ)上にデータを格納することが可能です。 DoMの使用目的は、サイズの小さい(64KiB以下)ファイルのパフォーマンス向上となります。 なお、DoMでMDT上に作成可能なコンポーネントサイズの最大値は 64KiB となります。
修正後：
グローバルスクラッチ領域ではData on MDT(DoM)機能を利用可能です。 DoM機能を有効にすることにより、サイズの小さいファイル(本サービスでは64KiB以下)に対する性能向上を期待できます。デフォルトは無効となっています。

2021-12-23 07:11 UTC, s-yama commented on ja/docs/storage.md
> +
谷村さんからコメント受領しました。下記を追記お願いします。(12/23 15時)

例）DoM機能を再度無効にする方法
　手順を書く
例）DoM機能が有効になっているかどうかを確認する方法
　手順を書く

2021-12-23 07:13 UTC, s-yama commented on ja/docs/storage.md
> +また、DoM 機能と一緒に[ストライプ機能](storage.md#advanced-option-file-striping)を設定可能です。
谷村さんからコメント受領しました。下記を追記お願いします。(12/23 15時)

DoMでのストライプでは、 〇〇個のmdtを利用可能です。

2021-12-24 06:35 UTC, merged