Add work around for the nccl error
aistairc/abci-docs pull request #318
Opened 2021-12-17 09:03 UTC by ABCI-FJSE

既知の問題のページに、pytorchとNCCLを使用する分散深層学習の実行に失敗する現象の回避策を追記しました。
ご確認よろしくお願い致します。

2021-12-20 00:44 UTC, u-kawasaki commented on en/docs/known-issues.md
> +| 2021/12/17 | Application | The distributed deep learning with pytorch and NCCL on the compute node (A) will be failed.<br>To avoid this issue, set the following environmental value in your job scri
"environmental value" should be expressed as "environment variable".

2021-12-20 09:40 UTC, ttakayuki approved these changes

2021-12-20 23:57 UTC, s-yama commented on en/docs/known-issues.md
> +| 2021/12/17 | Application | The distributed deep learning with pytorch and NCCL on the compute node (A) will be failed.<br>To avoid this issue, set the following environmental value in your job scri
英語を下記の通り修正お願いします。
修正前：The distributed deep learning with pytorch and NCCL on the compute node (A) will be failed.
修正後：A known issue has been identified that the execution of distributed deep learning using pytorch and NCCL fails on the compute node (A).

2021-12-21 00:00 UTC, s-yama requested changes
修正コメントを参照して、修正お願いします。

2021-12-21 07:00 UTC, s-yama approved these changes
私はこれで良いと思います。

2021-12-21 07:05 UTC, u-kawasaki approved these changes

2021-12-21 07:06 UTC, merged