Migration from /fs3 has done.
aistairc/abci-docs pull request #328
Opened 2022-02-04 01:06 UTC by u-kawasaki

2022-02-04 06:57 UTC, s-yama commented on ja/docs/faq.md
> +なお、**旧領域**のファイルを**新領域**へ移行する作業はすべてのコピーが完了し、次回のメンテナンスで **旧領域**(`/fs3/`)へのシンボリックリンクを置き換える作業を残すのみとなりました。
下記を修正お願いします。
修正前：次回のメンテナンス
修正後：2022年3月上旬のメンテナンス

2022-02-04 06:57 UTC, s-yama commented on ja/docs/faq.md
> +* **旧領域**`/group1/`および`/group2/`へのパスは**新領域**内のコピー先へのシンボリックリンクに置き換えられています。**旧領域**`/fs3/`への置き換えは次回のメンテナンス中に行いますのでしばらくお待ちください。
下記を修正お願いします。
修正前：次回のメンテナンス
修正後：2022年3月上旬のメンテナンス

2022-02-04 06:58 UTC, s-yama commented on ja/docs/faq.md
> +* これらのパス`/fs3/d00[1-2]/gAA50NNN`は、次回のメンテナンスで**新領域**内の移行先ディレクトリへのシンボリックリンクに置き換えられ、従来と同じパスでアクセス可能になります。
下記を修正お願いします。
修正前：次回のメンテナンス
修正後：2022年3月上旬のメンテナンス

2022-02-04 10:43 UTC, ttakayuki reviewed
ドキュメントありがとうございます。コメントしましたのでご確認ください。

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +
「計算ノード(A)と計算ノード(V)の違いが知りたい」のFAQ中に、データ移行の状況の説明は不要と思います。

```
**旧領域**(`/groups[1-2]/gAA50NNN`)のファイルは移行作業が完了したため、計算ノード(A)から**旧領域**と同じパスでアクセスすることができます。

なお、2021年4月より**旧領域**のファイルを**新領域**へ移行する作業も進めています。グループ領域のデータ移行については、FAQの[グループ領域のデータ移行について知りたい](faq.md#q-what-are-the-new-group-area-and-data-migration)を参照してください。
```

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +このため、新たに計算ノード(A)からアクセス可能なグループ領域(以下、**新領域**)を作成し、そちらへ移行した先へのシンボリックリンクに置き換えられます。**旧領域**`/group1/`および`/group2/`の移行作業は既に完了し、`/fs3/`もコピーが終了して、シンボリックリンクへの置き換えを待つのみとなっております。
最初の段落で話が終わってしまっているため、意味がよくわからないものになっています。
データ移行が完了したことを示したいのでしたら、375行第一段落のあとにnoteを追加するのがよいと思います。

```
!!! note
    2022年1月25日、旧領域の全てのデータコピーが完了しました。
    残り`/fs3へのシンボリックリンクの設定は、2022年3月上旬のメンテナンスで実施する予定です。
```

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +* **旧領域**のデータは下記の移行先ディレクトリにコピーされています。
データ移行についての「基本的な方針」なので、内容は変えないでよいと思います。
移行完了に伴う変更としては、最初の項目の「全利用者データのコピー完了は2021年度末の予定です。」を削除するだけでよいと思います。

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> -```
ここは運営(我々)がどういう作業をする/したのかを説明するために必要だと思います。

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +2020年度まで使用していたグループ領域(**旧領域**)の`/groups1`および`/groups2`についてはデータ移行が完了し、現在は**新領域**へのシンボリックリンクが設定されており、従来通りのパスで**新領域**に書き込みができるようになっています。このため、**旧領域**`/groups1`および`/groups2`に割り当てられていたGPFSファイルシステムにアクセスすることは
1文が長くてよくわからないです。
以下では如何でしょうか。

```
2020年度まで使用していたグループ領域(旧領域)の`/groups1`および`/groups2`についてはデータ移行が完了しました。
このため、旧領域`/groups1`および`/groups2`に割り当てられていたGPFSファイルシステムにアクセスすることはできません。
`/groups1`および`/groups2`は、新領域へのシンボリックリンクが設定されており、従来通りのパスで書き込みができます。
```

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +* データ移行完了後、**旧領域**`/groups[1-2]/gAA50NNN`および`/fs3/d00[1-2]/gAA50NNN/`に割り当てられていた GPFS ファイルシステムにはアクセスできなくなります。
旧領域がGPFSファイルシステムのことですよね?
"割り当てられていた GPFS ファイルシステムには" は不要ではないでしょうか。

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +| `/groups1/gAA50NNN/`     | Yes      | No[^5]   | No[^5] | `/projects/datarepository/gAA50NNN/migrated_from_SFA_GPFS/`[^1]  | d002利用者向け |
/groups1のデータ移行が完了しているなら、 書き込み、削除の項目をYesにすればよいのではないでしょうか?

2022-02-04 10:43 UTC, ttakayuki commented on ja/docs/faq.md
> +[^5]: 2022年3月上旬のメンテナンス後に書き込み/削除が可能な新領域へのシンボリックリンクに置き換わります。
`[^4]`がこのページのどこからもリンクされていないようです。上のコメントに書いたように、/groups1の移行が完了しているならこのfootnoteは不要だと思います。

`[^5]`のnoteは`[^4]`に変更するとともに、内容は「/fs3/ 内の全データが移行完了後に書き込み/削除が可能になります。」のままでよいのではないでしょうか?

2022-02-07 08:32 UTC, u-kawasaki commented on ja/docs/faq.md
> +* データ移行完了後、**旧領域**`/groups[1-2]/gAA50NNN`および`/fs3/d00[1-2]/gAA50NNN/`に割り当てられていた GPFS ファイルシステムにはアクセスできなくなります。
migrated_from_SFA_GPFS/ を、旧領域のバックアップのように誤認している利用者様がいらっしゃいました。/groups[1-2] に割り当てられていた GPFS ファイルシステムはもはや利用できず、移行先へのシンボリックリンクであることを明示しておく必要があると思われます。

2022-02-07 08:32 UTC, u-kawasaki commented on ja/docs/faq.md
> +
/fs3 のユーザーは未だに計算ノード(A) から旧領域のデータにアクセスすることができておらず、移行作業の進捗状況を知りたがっていると考えられるので、この項目は3月のメンテナンスが終わるまで必要と考えられます。

2022-02-08 02:55 UTC, s-yama commented on ja/docs/faq.md
> +なお、**旧領域**のファイルを**新領域**へ移行する作業はすべてのコピーが完了し、2022年3月上旬のメンテナンスで **旧領域**(`/fs3/`)をシンボリックリンクを置き換える作業を残すのみとなりました。
下記を修正お願いします。
修正前：**旧領域**(`/fs3/`)をシンボリックリンクを置き換える
修正後：
案１：**旧領域**(`/fs3/`)をシンボリックリンクに置き換える
案２：**旧領域**(`/fs3/`)をシンボリックリンクで置き換える

2022-02-09 02:57 UTC, ttakayuki commented
コミット b0e9df4 の時点で以下の点が不明です。

* 377行. ヘッダー「概要」とは?「概要」自体にあまり意味がないため、ヘッダーに追加する必用がわかりません。また、書かれている内容が概要ではないように思います。
* 379行. 「移行作業を行っています。」何の移行作業を行っているのかわかりません。移行作業の内容を説明する前に「移行作業を行っている」と言われても何のことかわからないです。
* 384行. 「旧領域、新領域ともにすべてのインタラクティブノードと計算ノード(V)からアクセスできます。」 旧領域はもうどこからもアクセスできないという理解なのですが違うのでしょうか?
* 384行. 379行では「移行作業を行っています。」と書かれていますが、384行では「このため計算ノード(A)からもアクセス可能な新領域にデータを移行し、従来のパスは移行先へのシンボリックリンクに置き換えます。」とこれから行う作業のことがかかれており、混乱します。
* 388行. 箇条書きがいきなり始まりますが、何の箇条書きかをタイトルだけでもいいので説明してください。
* 388行. 「既に完了しました。」既にとありますが、いつ完了したのかが不明です。日付を追加するか、単に「完了しました」だけでよいと思います。
* 390行. ユーザーガイドはアナウンス文書ではないので、「しばらくお待ちください。」は不要だと思います。
* 391行. 「コピーされています。」ここは「コピーしました」でよいのではないでしょうか。
* 415行. PR329だと残したままとしていますが、新領域は現在はどういう状態なのでしょうか? migrated_*ディレクトリも含めアクセス可能?

2022-02-15 02:01 UTC, s-yama requested changes
すみません、今回の修正箇所ではないのですが、下記を修正お願いします。
修正前：User groups who are using the Old Area /fs3/ have been allocated the New Area /projects/ since mid July.
修正後：User groups who are using the Old Area /fs3/ have been allocated the New Area /projects/ since mid July 2021.

下記についても修正お願いします。
修正前：The process of transferring all data from the Old Area to the New Area has already been completed.
修正後：The process of transferring all data from the Old Area to the New Area has already been completed on January 25, 2022.

2022-02-15 02:46 UTC, s-yama approved these changes
多々修正ありがとうございました。私はこれで良いと思います。

戸澤さん、いかがでしょうか。

2022-02-15 04:47 UTC, ttakayuki reviewed
「Q. グループ領域のデータ移行について知りたい」は「データ移行」が何なのかを知るためのエントリなのに、「データ移行」が何であるかわかった上での文章になってしまっています。

2022-02-15 04:47 UTC, ttakayuki commented on ja/docs/faq.md
文章の意味がわかりません。

> しかし、2021年5月に新規導入された計算資源(計算ノード(A))からは移行前の**旧領域**にアクセスすることができませんでした。

前文は新領域の話をしていて、その後旧領域の話をしており、「しかし」でつながらないと思うのですが?
また、「しかし、...アクセスすることができませんでした。」だと、今はアクセスできるように読めます。

> このため計算ノード(A)からもアクセス可能な**新領域**に**旧領域**にあったデータをコピーし、

この文も「このため」で前文とつながっていません。
「旧領域にあったデータ」というのが何のことを言っているのかわかりません。
「従来のパス」とは?

2022-02-15 04:47 UTC, ttakayuki commented on ja/docs/faq.md
> +	**旧領域**`/fs3/`へのパスは2022年3月上旬のメンテナンス中にの置き換えられます。
> メンテナンス中にの置き換えられます。

脱字でしょうか?

2022-02-15 04:47 UTC, ttakayuki commented on ja/docs/faq.md
> +* `/fs3/d00[1-2]/gAA50NNN`へのシンボリックリンクの設定は、2022年3月上旬のメンテナンスでの実施を予定しています。以後、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。
> 以後、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。

「以後」とは? どの時点のことを指していますか?

2022-02-15 06:05 UTC, u-kawasaki commented on ja/docs/faq.md
> +* `/fs3/d00[1-2]/gAA50NNN`へのシンボリックリンクの設定は、2022年3月上旬のメンテナンスでの実施を予定しています。以後、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。
メンテナンス後のつもりなのですが、それ以外に誤解されますか?

2022-02-15 06:05 UTC, u-kawasaki commented on ja/docs/faq.md
> +	**旧領域**`/fs3/`へのパスは2022年3月上旬のメンテナンス中にの置き換えられます。
修正します。

2022-02-15 06:06 UTC, u-kawasaki commented on ja/docs/faq.md
> +ストレージシステムの増強にともないグループ領域の構成が変更され、2020年度まで使用していたグループ領域(以下、**旧領域**)から新しいグループ領域(以下、**新領域**)への移行作業を行っています。
この3つの段落で簡潔に説明したつもりだったのですが、語順がまずいということでしょうか? 
先に結論、後で解説(それも直後)というのは普通のことだと思います。

2022-02-15 06:06 UTC, u-kawasaki commented on ja/docs/faq.md
確かにシステムの全体像を知らない利用者が、旧領域＝「昨年度以前のグループに割り当てられていた共有領域として利用していた GPFS 上の領域」と認識するためには他を読みまくる必要がありますね。
もう少し工夫をしてみます。

2022-02-15 06:46 UTC, ttakayuki commented on ja/docs/faq.md
> +ストレージシステムの増強にともないグループ領域の構成が変更され、2020年度まで使用していたグループ領域(以下、**旧領域**)から新しいグループ領域(以下、**新領域**)への移行作業を行っています。
> 語順がまずいということでしょうか?

いえ、コメントしたとおりです。
「移行作業を行います」なら、この段以降に説明がくると読めますが、「移行作業を行なっている」と進行形で書いている以上、行なっている移行作業とは何か(作業内容)を先に説明しないと意味が通じません。

2022-02-15 06:56 UTC, ttakayuki commented on ja/docs/faq.md
> +* `/fs3/d00[1-2]/gAA50NNN`へのシンボリックリンクの設定は、2022年3月上旬のメンテナンスでの実施を予定しています。以後、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。
メンテナンス後かどうかが「以後」だけではわかりません。

> シンボリックリンク設定後、旧領域に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。

の方がわかりやすいのではないでしょうか?

2022-02-15 07:24 UTC, u-kawasaki commented on ja/docs/faq.md
> +* `/fs3/d00[1-2]/gAA50NNN`へのシンボリックリンクの設定は、2022年3月上旬のメンテナンスでの実施を予定しています。以後、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできなくなります。
修正しました。

2022-02-15 07:24 UTC, u-kawasaki commented on ja/docs/faq.md
> +ストレージシステムの増強にともないグループ領域の構成が変更され、2020年度まで使用していたグループ領域(以下、**旧領域**)から新しいグループ領域(以下、**新領域**)への移行作業を行っています。
こちらももう少し時間下さい。

2022-02-17 05:37 UTC, ttakayuki reviewed
コメントしましたので、確認をお願いします。

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +ストレージシステムの増強にともないグループ領域の構成が変更され、2020年度まで使用していたグループ領域(以下、**旧領域**)から新しいグループ領域(以下、**新領域**)へのデータ移行を行います。
一文が長いため分かりにくいです。文を区切ったほうがわかりやすいと思います。

```
ストレージシステムの増強にともない、グループ領域の構成変更を行います。
具体的には、2020年度まで使用していたグループ領域(以下、旧領域)から新し
いグループ領域(以下、新領域)へのデータ移行を行います。
```

または一行で説明したいなら以下でしょうか。

```
ストレージシステムの増強にともないグループ領域の構成を変更し、2020年度まで使用
していたグループ領域(以下、旧領域)のデータを新しいグループ領域(以下、新領域)へ
移行します。
```

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +2021年5月に新規導入された計算資源([計算ノード(A)](#q-what-is-the-difference-between-compute-node-a-and-compute-node-v))からは**旧領域**にアクセスすることができません。このため、計算ノード(A)を含むすべての計算ノードおよびインタラクティブノードからアクセス可能な**新領域**に**旧領域**にあったデータをコピ
この文章だと、計算ノード(A)が旧領域にアクセスできないから、新領域を用意してそこにデータ移行しているように読めませんか? データ移行する理由が変わってしまっているような?
また、一文が長いため分かりにくいです。文を区切ったほうがわかりやすいと思います。
以下は如何がでしょうか?

```
2021年5月に新規導入された計算資源(計算ノード(A))は旧領域にアクセスできません。
このため、旧領域上のデータを計算ノード(A)からアクセス可能な新領域にコピーします。
コピー後、旧領域上のパスでアクセスできるよう、旧領域のパスは新領域内の移行先ディレクトリへのシンボリックリンクに置き換えられます。
```

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +	**旧領域**`/fs3/`へのパスは2022年3月上旬のメンテナンス中に**新領域**内のコピー先へのシンボリックリンクに置き換えられます。
用語を合わせた方がわかりやすいように思います。
コピー先へのシンボリックリンク -> 移行先ディレクトリへのシンボリックリンク

```
* 旧領域/groups1/および/groups2/のパスは新領域内の移行先ディレクトリへのシンボリックリンクに置き換わっています。
* 旧領域/fs3/のパスは2022年3月上旬のメンテナンス中に新領域内の移行先ディレクトリへのシンボリックリンクに置き換えられます。
```

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +**旧領域**のデータは下記の移行先ディレクトリにコピーしました。
文章を分けた方がわかりやすいように思いました。
また、現在の説明(継続)となるので、ここは過去形にする必用はないと思います。
以下では如何がでしょうか?

```
旧領域のデータを新領域へ移行しています。移行先は次の表を参照してください。
```

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +データ移行後に確認のため以下のコマンドを実行しました。
ここも特に過去形にする必用はないと思います。

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +* 2021年8月11日、**旧領域**を読み取り専用に変更しました。また、2022年1月25日、**旧領域**のすべてのデータコピーが完了しました。データの保存には**新領域**を利用してください。
読み取り専用にしたことと、データコピーが完了したことはつながらないので、「また、」以降は項目を分けた方がいいと思います。

```
* 2021年8月11日、旧領域を読み取り専用に変更しました。
* 2022年1月25日、旧領域のすべてのデータコピーが完了しました。データの保存には新領域を利用してください。
```

2022-02-17 05:37 UTC, ttakayuki commented on ja/docs/faq.md
> +* `/groups[1-2]/gAA50NNN`は移行先へのシンボリックリンクに置き換えられたため、**旧領域**に割り当てられていたGPFSファイルシステムにはアクセスできません。
umountしたからアクセスできないとかならわかりますが、シンボリックリンクに置き換えたから、GPFSファイルシステムにアクセスできないという理由がよくわかりません。
シンボリックリンクを設定したから、という理由は不要ではないでしょうか?

```
* 旧領域に割り当てられていたGPFSファイルシステム上の/groups[1-2]/gAA50NNNにはアクセスできません。
```

2022-02-17 05:47 UTC, u-kawasaki commented on ja/docs/faq.md
> +2021年5月に新規導入された計算資源([計算ノード(A)](#q-what-is-the-difference-between-compute-node-a-and-compute-node-v))からは**旧領域**にアクセスすることができません。このため、計算ノード(A)を含むすべての計算ノードおよびインタラクティブノードからアクセス可能な**新領域**に**旧領域**にあったデータをコピ
> 計算ノード(A)が旧領域にアクセスできないから、新領域を用意してそこにデータ移行しているように読めませんか? 
計算ノード(A) で利用できる GPFS のライセンスがないから、新領域を lustre にしたと理解しているのですが

2022-02-17 06:03 UTC, u-kawasaki commented on ja/docs/faq.md
> +	**旧領域**`/fs3/`へのパスは2022年3月上旬のメンテナンス中に**新領域**内のコピー先へのシンボリックリンクに置き換えられます。
修正します。

2022-02-17 06:10 UTC, u-kawasaki commented on ja/docs/faq.md
> +**旧領域**のデータは下記の移行先ディレクトリにコピーしました。
コピーは既に完了しているので意図的に過去形にしています。

2022-02-17 06:11 UTC, u-kawasaki commented on ja/docs/faq.md
> +データ移行後に確認のため以下のコマンドを実行しました。
これも既に完了しているので過去形です。

2022-02-17 10:21 UTC, ttakayuki commented on ja/docs/faq.md
> +2021年5月に新規導入された計算資源([計算ノード(A)](#q-what-is-the-difference-between-compute-node-a-and-compute-node-v))からは**旧領域**にアクセスすることができません。このため、計算ノード(A)を含むすべての計算ノードおよびインタラクティブノードからアクセス可能な**新領域**に**旧領域**にあったデータをコピ
第一段落では、

> グループ領域の構成を変更したので、旧領域のデータを新領域へ移行する

とあるのに、その次の段では

> 計算ノード(A)は、旧領域にアクセスできません。このため、旧領域のデータを新領域にコピーします。

となっており、主題が切り替わっていませんか?という話です。

今公開されている文章は、

> 旧領域は、計算ノード(A)からアクセスできません。このため、計算ノード(A)からアクセスできるグループ領域を作成し、そちらへの移行を行います

と主題はあくまで旧領域であり、変更したのはなぜでしょう?


もう一点。

> 計算ノード(A)を含むすべての計算ノードおよびインタラクティブノードからアクセス可能な新領域

は、修飾が長いです。直前で計算ノード(A)のことしか書いていないのにここまで飾る必用はないと思います。

新領域がどこからアクセスできるかは、3段落目で説明していたのでそれを戻すでよいのではないでしょうか?
もしくは、文章を分けた方がいいように思います。

文章をわけつつ、移行作業を説明するなら以下のような文章になるでしょうか?

```
新領域は、[計算ノード](system-overview.md#compute-node)および[インタラクティブノード](system-overview.md#interactive-node)からアクセスすることができます。
ただし、2021年5月に新規導入された計算ノード(A)は旧領域にアクセスすることができません。
このため、旧領域上のデータを新領域へコピーし、計算ノード(A)から旧領域のデータを利用できるようにします。
また、データをコピーした後、旧領域と同じパスでアクセスできるように、旧領域のパスを新領域内の移行先ディレクトリへのシンボリックリンクに置き換えます。
```

2022-02-17 10:39 UTC, ttakayuki commented on ja/docs/faq.md
> +**旧領域**のデータは下記の移行先ディレクトリにコピーしました。
通しで読んでみるとわかると思いますが、読んでる途中で文体が変わるため読みにくいです。
作業の説明なので現在形でよいのではないでしょうか?

```
--(略)--

なお、2021年度以降に新規に作成されたABCIグループについては、新領域のみが割り当てられるためデータ移行の対象ではなく、データ移行の影響を受けません。

旧領域のデータは下記の移行先ディレクトリにコピーしました。

データ移行作業には以下のコマンドを用いています。

データ移行後に確認のため以下のコマンドを実行しました。
```

```
なお、2021年度以降に新規に作成されたABCIグループについては、新領域のみが割り当てられるためデータ移行の対象ではなく、データ移行の影響を受けません。

旧領域のデータは下記の移行先ディレクトリにコピーします。

データ移行作業には以下のコマンドを用います。

データ移行後に確認のため以下のコマンドを実行します。
```

2022-02-18 01:44 UTC, ttakayuki commented on ja/docs/faq.md
> +**旧領域**のデータは下記の移行先ディレクトリにコピーしました。
時制はメインの話ではないです。
データ移行に関する説明をしている文において、急に報告が入っているように読めます。
報告としての文章としたいのでしたら、セクションを分けたほうがわかりやすいように思います。`### 新領域について` 内がよいでしょうか。
また、「データ移行作業には以下のコマンドを用いています。」は過去形にしなかったのはなぜでしょう? (すみません、私がそういう修正依頼をしたんでしたっけ?)
「用いました」や「実行しました」の方がよいのではないでしょうか?

2022-02-18 04:18 UTC, ttakayuki approved these changes
一点、402行の余計な句点の削除をお願いします。
それ以外はOKと思います。

2022-02-18 04:18 UTC, ttakayuki commented on ja/docs/faq.md
> +データ移行作業には以下のコマンドを実行しました。。
句点が一つ多いので削除をお願いします。

2022-02-18 04:25 UTC, u-kawasaki commented on ja/docs/faq.md
> +データ移行作業には以下のコマンドを実行しました。。
修正しました。

2022-02-22 06:28 UTC, s-yama approved these changes
私はこれで良いと思います。修正ありがとうございました。

2022-02-22 06:30 UTC, merged