mod faq.md
aistairc/abci-docs pull request #336
Opened 2022-03-18 10:51 UTC by ABCI-FJSE

山本様
チケット4368 ( https://my.redmine.jp/aist.rp-ith/issues/4368 ) でご依頼のありました、inode使用状況の確認手順をfaq.mdに記載しました。
お手数ですが、ご確認のほどよろしくお願いします。

2022-03-22 02:48 UTC, u-kawasaki approved these changes

2022-03-24 08:07 UTC, ttakayuki reviewed
faq.mdに追加していただいていますが、情報としてはstorage.mdの「グループ領域 {#group-area}」内に追加するのがよいのではないでしょうか?

```
## グループ領域 {#group-area}

### inode使用率の確認方法

```

2022-03-24 08:07 UTC, ttakayuki commented on ja/docs/faq.md
> +
「ABCIグループの下一桁」よりは「ABCIグループ名の下一桁」のほうがよいと思います。

2022-03-25 08:06 UTC, s-yama approved these changes
戸澤さんのコメントについて反映を検討お願いします。

それ以外について、私は良いと思います。

2022-03-25 08:11 UTC, y-tanimura commented on ja/docs/faq.md
> +
決め方の記述自体が不要と思います。バランスを取るために例外を作るという議論もしていますので、後で問題になります。

2022-03-25 08:19 UTC, u-kawasaki commented on ja/docs/faq.md
> +
バランスをとるために、来年度の新規グループは下1桁の 1 と 6 を飛ばして発行するとのことなので、例外は作られないと思われますが。

2022-03-25 10:45 UTC, stakizawa approved these changes

2022-03-30 07:52 UTC, ABCI-FJSE commented
山本様
ご指摘いただいた箇所について修正を実施しました。ご確認のほどよろしくお願いします。

2022-03-30 08:19 UTC, stakizawa approved these changes

2022-03-30 08:30 UTC, y-tanimura requested changes
割り当てルールの記載は削除すること。

2022-03-31 04:33 UTC, ABCI-FJSE commented
山本様
本日(3/31)、電話でご相談させていただいた内容で修正しました。
ご確認のほどよろしくお願いします。

2022-03-31 05:53 UTC, s-yama approved these changes
谷村さんよりSLACKで3/31 13:50頃に「最新の変更で OK です。」のメッセージを受領しました。
また、私も、これで良いと思います。

2022-03-31 07:49 UTC, merged