mod ABCI portal user manual
aistairc/abci-docs pull request #337
Opened 2022-03-23 03:50 UTC by ABCI-FJSE

2021年度利用者ポータル改修に伴う、利用手引きの修正です。
ご確認のほどよろしくお願いします。

2022-03-24 02:44 UTC, u-kawasaki reviewed
先日の会議でも指摘した通り、英文の `1.2 Apply for group` の最後の行に分かち書きの乱れがあります。
修正の上 1_02.png も差し替えてください。

2022-03-25 01:53 UTC, ttakayuki reviewed
コメントしますのでご確認ください。

2022-03-25 01:53 UTC, ttakayuki commented on portal/en/docs/03.md
> +### 3.5.5. Set Administorator Authority {#355-set-administorator-authority}
Administratorのtypoがあります。

2022-03-25 01:53 UTC, ttakayuki commented on portal/ja/docs/03.md
> +### 3.5.5. 利用管理者権限設定 {#355-set-administorator-authority}
フラグメントのadministratorにtypoがあります。

2022-03-30 07:59 UTC, ABCI-FJSE commented
ご指摘いただいた箇所について修正を実施しました。
ご確認のほどよろしくお願いします。
・英文の 1.2 Apply for group の最後の行に分かち書きの乱れ(1_02.png)
・administratorのtypo修正

2022-03-30 08:17 UTC, ABCI-FJSE commented
なお、以下のチケットで修正予定の画像についても回答を頂いたものから順に、後日プッシュ予定です。
https://my.redmine.jp/aist.rp-ith/issues/4447
https://my.redmine.jp/aist.rp-ith/issues/4462

2022-03-31 00:14 UTC, u-kawasaki approved these changes

2022-04-06 02:40 UTC, s-yama requested changes
https://my.redmine.jp/aist.rp-ith/issues/4462 の修正に伴い、「利用者ポータルの手引き」の下記の箇所が修正されるべきと思いますが、反映されていないように見えます。ご確認お願いいたします。

2.1.1. 初回ログイン

2022-04-06 02:52 UTC, u-kawasaki approved these changes

2022-04-06 04:08 UTC, s-yama approved these changes

2022-04-06 04:09 UTC, s-yama approved these changes
修正が反映されていることを確認しました。approveします。

2022-04-06 04:28 UTC, merged