Update bucket encryption
aistairc/abci-docs pull request #368
Opened 2022-07-13 07:20 UTC by ABCI-FJSE

Scality Ringの新機能に関連する利用手引きの修正を実施しました。
ご確認のほどよろしくお願いいたします。

- S3API互換コマンドでの暗号化バケット作成

(PR #348 から「S3API互換コマンドでの暗号化バケット作成」のみを抜き出しています。)

2022-07-14 07:36 UTC, ttakayuki reviewed
すみません、#348 でちゃんとレビューできていませんでした。
コメントしますので対応をお願いします。

2022-07-14 07:36 UTC, ttakayuki commented on ja/docs/abci-cloudstorage/encryption.md
> +SSEを有効にしたバケットかどうかを判別するには、`aws s3api get-bucket-encryption` を実行します。
こちらも用語を合わせてください。

```
デフォルト暗号化を有効にしたバケットかどうかを判別するには、...
```

2022-07-14 07:36 UTC, ttakayuki commented on ja/docs/abci-cloudstorage/encryption.md
> +以下では、dataset-s0001 バケットでSSEが有効になっているかを確認しています。 `"SSEAlgorithm": "AES256"` という情報が含まれているため、dataset-s0001 はデフォルト暗号化を有効にしたバケットであるといえます。この情報が含まれていない場合は、デフォルト暗号化が有効でないバケットであることを示しています。
以下はいかがでしょうか?

```
以下では、`dataset-s0001`バケットのデフォルト暗号化が有効かどうかを確認しています。 
`aws s3api get-bucket-encryption`コマンドの出力に、`"SSEAlgorithm": "AES256"`が含まれていればバケットのデフォルト暗号化は有効です。この情報が含まれていない場合、バケットのデフォルト暗号化は有効ではありません。
```

2022-07-14 07:36 UTC, ttakayuki commented on ja/docs/abci-cloudstorage/encryption.md
すみません、今回の修正とは別で恐縮なのですが。
最初にある、略称と正式名称の修正をお願いします。
`CSE (Client-Side Encryption)` -> `Client-Side Encryption (CSE)`
`SSE (Server-Side Encryption)` -> `Server-Side Encryption (SSE)`

2022-07-14 08:16 UTC, u-kawasaki commented on ja/docs/abci-cloudstorage/encryption.md
> +例えば、'dataset-s0001' というバケットで SSE を有効化する場合は以下のように実行します。
「デフォルト」というカタカナ語は我々は普通に使っていますが、一般的とは言い難く、経済用語では「破綻」を意味したりします。
ここは「バケットの暗号化を既定で有効にする」のように訳すべきではないでしょうか。

2022-07-14 09:26 UTC, ttakayuki commented on ja/docs/abci-cloudstorage/encryption.md
> +例えば、'dataset-s0001' というバケットで SSE を有効化する場合は以下のように実行します。
AWS S3の日本語リファレンスでも「デフォルト暗号化」を使用しているので、ここは合わせた方が混乱は少ないと思われます。

https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/default-bucket-encryption.html

また、この機能(default bucket encryption)は、バケットにオブジェクトを保存した場合の初期暗号化設定を行うものなので、コンピューター用語としての「デフォルト」を使うのが妥当だと思います。
「デフォルト」を使わずに説明する方が大変かと。

2022-07-14 23:55 UTC, u-kawasaki commented on ja/docs/abci-cloudstorage/encryption.md
> +例えば、'dataset-s0001' というバケットで SSE を有効化する場合は以下のように実行します。
AWS でそういう訳語が既に用いられているのですね。
昭和世代の私にとって、 default → 既定 と訳すのが常識であり、違和感しかないのですが、「アルファベットをカタカナに変換するのは翻訳とは言わない」と文部省・国語審議会から指導されていたのは今は遠い昔の話。
ABCI を操作している利用者の主力が平成世代であることを考えると受け入れなければいけないのでしょう。

2022-07-15 01:28 UTC, u-kawasaki approved these changes

2022-07-22 07:40 UTC, ttakayuki reviewed
ありがとうございます。日本語版の修正を確認しました。
英語版についていくつかtypoがありましたので修正をお願いします。

2022-07-22 07:40 UTC, ttakayuki commented on en/docs/abci-cloudstorage/encryption.md
> +Data is encrypted when it is stored in disks after uploading to ABCI Cloud Storage. Encrypted data is decryped after retrieving data from the disk. Then the data will be downloaded. Thus, data are de
"Encrypted data is decryped" decrypted のtypoの修正をお願いします。

また、16行目 "Encryption with key registerd" のregisteredの修正もお願いいたします。

```
| SSE-KMS | Encryption with key registerd to Key Management Service. |
```

2022-07-22 07:40 UTC, ttakayuki commented on en/docs/abci-cloudstorage/encryption.md
> +You can set the default encryption befavior for a bucket. If you enable default encryption for a bucket, all objects will have encryption when stored in the bucket.
"You can set the default encryption befavior " behavior のtypoの修正をお願いします。

2022-07-25 02:19 UTC, ABCI-FJSE commented
typoを修正いたしましたので、ご確認のほどよろしくお願いいたします。

2022-07-25 04:07 UTC, ttakayuki approved these changes
修正を確認しました。ありがとうございました。

2022-07-28 01:16 UTC, s-yama commented on ja/docs/abci-cloudstorage/encryption.md
> +    ABCI クラウドストレージでは運用開始より、SSE を有効にしたバケットを作成する create-encrypted-bucket コマンドを提供してきましたが、create-encrypted-bucket コマンドは2022年8月を目処に提供を終了する予定です。
create-encrypted-bucketコマンドの後継コマンドを紹介すべきではないでしょうか。
文章の例としては、下記のようなものを想定しています。
「8月より後は、create-encrypted-bucketコマンドの代わりに、aws-cliコマンドを利用ください。」

2022-07-28 01:16 UTC, s-yama commented on ja/docs/abci-cloudstorage/encryption.md
> +クラウド向けのストレージにおいては、一般的に、クライアント側で暗号化する Client-Side Encryption (CSE) とサーバ側で暗号化する Server-Side Encryption (SSE) があります。SSEはストレージ側での機能提供が必要であり、ABCIクラウドストレージではSSE機能をサポートしています。
後半で「一方、ABCIクラウドストレージではCSEの利用は可能です。」と書かれているのですが、ここには、「ABCIクラウドストレージではSSE機能をサポートしています。」と書かれています。
ここに、CSEが利用可能であることを書かない理由は何でしょうか？特に理由がないのであれば、CSE利用可能であうることを書いていただけないでしょうか。
文章の例としては、下記のようなものを想定しています。
「SSEはストレージ側での機能提供が必要であり、ABCIクラウドストレージではSSE機能をサポートしています。また、ABCIクラウドストレージではCSEの機能（ただしKMS(Key Management Service)を除く）が利用可能です。」

2022-07-28 01:24 UTC, s-yama commented on en/docs/abci-cloudstorage/encryption.md
> +    Since the start of operation, ABCI Cloud Storage has provided the create-encrypted-bucket command to create a bucket with activated enabled, but the create-encrypted-bucket command is scheduled t
to create a bucket with activated enabled,　の個所に、「SSE有効化」という情報が含まれているべきと思います。
例えば下記のような文章はいかがでしょうか。
修正前：ABCI Cloud Storage has provided the create-encrypted-bucket command to create a bucket with activated enabled, 
修正後：ABCI Cloud Storage has provided the create-encrypted-bucket command to create an SSE-enabled bucket,

また、日本語箇所にもコメントしましたが、 create-encrypted-bucket の後継コマンド aws-cli をここで紹介すべきと思います。ご検討お願いします。

2022-07-28 01:32 UTC, s-yama requested changes
コメントを書きましたので、ご検討お願いします。

2022-07-28 01:32 UTC, s-yama commented on en/docs/abci-cloudstorage/encryption.md
> +    There is no change to the encryption of the objects that existed in the bucket before default encryption was enabled.
下記の修正はいかがでしょうか。ご検討お願いします。
修正前：There is no change to the encryption of the objects that existed in the bucket before default encryption was enabled.
修正後：Objects, which existed in the bucket before the bucket's default encryption was enabled, are not encrypted.

2022-08-01 06:06 UTC, ABCI-FJSE commented
ご指摘いただいた箇所を修正いたしましたので、ご確認のほどよろしくお願いいたします。

2022-08-01 11:20 UTC, ttakayuki commented on ja/docs/abci-cloudstorage/encryption.md
> +クラウド向けのストレージにおいては、一般的に、クライアント側で暗号化する Client-Side Encryption (CSE) とサーバ側で暗号化する Server-Side Encryption (SSE) があります。SSEはストレージ側での機能提供が必要であり、ABCIクラウドストレージではSSE機能をサポートしています。
修正していただいた後で申し訳ないです。

山本様、CSEはクライアント側でデータの暗号化/復号を行い、クラウドストレージとしては単に暗号化されたデータを保存するだけですので、「ABCIクラウドストレージではCSEの機能が利用可能」は誤りです。(CSEという機能はクラウドストレージにはありません)

「一方、ABCIクラウドストレージではCSEの利用は可能です。」だとCSEの説明が端折りすぎてわかりにくいのでしたら、以下のような文章はいかがでしょうか? 
(18行目への修正、1段落目の「また、ABCIクラウドストレージではCSEの機能（ただし...」は削除。)

```
CSEはデータの暗号化および復号を利用者が行い、暗号化されたデータをABCIクラウドストレージに保存します。
ABCIクラウドストレージではCSEを利用できます。

ただし、ABCIクラウドストレージではKey Management Service(KMS)を提供していないため、KMSに保存されている暗号キーを利用してのCSEは利用できません。
CSEの詳しい説明は、[Protecting Data Using Client-Side Encryption](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html) をご参照ください。
```

2022-08-03 04:26 UTC, s-yama commented on ja/docs/abci-cloudstorage/encryption.md
> +クラウド向けのストレージにおいては、一般的に、クライアント側で暗号化する Client-Side Encryption (CSE) とサーバ側で暗号化する Server-Side Encryption (SSE) があります。SSEはストレージ側での機能提供が必要であり、ABCIクラウドストレージではSSE機能をサポートしています。
ABCI常駐SE様へ
戸澤さんのこのコメントを反映お願いします。

2022-08-03 07:19 UTC, ABCI-FJSE commented on ja/docs/abci-cloudstorage/encryption.md
> +クラウド向けのストレージにおいては、一般的に、クライアント側で暗号化する Client-Side Encryption (CSE) とサーバ側で暗号化する Server-Side Encryption (SSE) があります。SSEはストレージ側での機能提供が必要であり、ABCIクラウドストレージではSSE機能をサポートしています。
修正いたしましたのでご確認のほどお願いたします。

2022-08-03 08:59 UTC, s-yama approved these changes
修正ありがとうございました。
私はこれで良いと思います。

2022-08-03 13:21 UTC, y-tanimura approved these changes

2022-08-04 00:43 UTC, ttakayuki approved these changes
ありがとうございます、修正を確認しました。

2022-08-04 07:41 UTC, u-kawasaki approved these changes

2022-08-04 07:54 UTC, merged