Fj20230222 01
aistairc/abci-docs pull request #392
Opened 2023-03-09 04:29 UTC by ABCI-FJSE

2022年度ABCI利用者ポータル改修に関する、利用手引きの修正となります。
ご確認のほどよろしくお願いします。

2023-03-09 04:45 UTC, ttakayuki commented
ごめんなさい。ポータルガイドの場合はマージ先はmasterブランチでいいんでしたっけ?

2023-03-09 05:07 UTC, ttakayuki commented
度々すみません、確認したところ利用者ポータルガイドのPRもユーザーガイドと同様のポリシーで運用していましたので、マージ先をdevel-202303ブランチに変更しました。

2023-03-09 09:47 UTC, u-kawasaki requested changes
portal/en/docs/img/1_01.png , etc. 

3rd line with hyper-link 
Agreement of ABCI Use based on the Joint Research with AIST (Effective on 2023/04/01) 
in the screen shot of "Agree to Terms of Use" should have "(Sorry, Japanese only)" . 

portal/en/docs/img/2_03_2.png 

The URL in the bottom line "https://abci.ai/ja/how_to_use/user_support.html" should be "https://abci.ai/en/how_to_use/user_support.html"

2023-03-10 05:56 UTC, taguchi-k08 approved these changes

2023-03-10 06:19 UTC, taguchi-k08 approved these changes

2023-03-14 03:12 UTC, s-yama approved these changes
利用の手引きの作成ありがとうございました。
私はこれで良いと思います。

2023-03-14 06:30 UTC, ABCI-FJSE commented
河崎様のコメントに対する修正(英版のスクリーンショットを4枚変更)を実施いたしました。ご確認のほどよろしくお願いします。
また、画面上の"ユーザサポートページへのURL"についてですが、既存のパスワード再発行時の画面で日本語表示のみだったため、日英切り替わる形に修正を加えました。

2023-03-14 06:38 UTC, u-kawasaki approved these changes
The corrections have been confirmed.
They looks OK.

2023-03-15 03:01 UTC, merged